# =============================================================================
# SERVICEMONITOR — inventory-service
# =============================================================================
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: inventory-service-monitor
  namespace: taller-monitoreo
  labels:
    app: inventory-service
    monitoring: "enabled"
spec:
  selector:
    matchLabels:
      app: inventory-service
  namespaceSelector:
    matchNames:
      - taller-monitoreo
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_name]
          targetLabel: pod
        - sourceLabels: [__meta_kubernetes_namespace]
          targetLabel: namespace
